### Create a school
POST http://localhost:80/school/
Content-Type: application/json

{
  "name": "UNEFA",
  "type": "UNIVERSITY",
  "municipalityID": "1ed11879-bd04-4233-ad4a-b6143d8a959b"
}

### Get school
GET http://localhost:80/school/b0d2e5f4-f8d4-4d7c-b8a9-d0e0f0a3d1b2
Content-Type: application/json
