### Create a user
POST http://localhost/school/user/
Content-Type: application/json

{
  "email": "test6@test.com",
  "firstname": "Shammaeli",
  "lastname": "Bien-Aisé",
  "pid": {
    "number": "V-12345569"
  }
}