### Create a user
POST http://localhost/school/user/
Content-Type: application/json

{
  "email": "test@test.com",
  "firstname": "Shammael",
  "lastname": "Bien-Aisé",
  "pid": {
    "number": "V-12345678"
  }
}